version: '3.9'  # Updated to a valid Docker Compose version
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Corrected the path
      - ./docker/mysql/data:/var/lib/mysql
